package models;

public class GrammarBuilder {

    public static Grammar build() {
        Grammar grammar = new Grammar();
        grammar.addRule(new Rule("<S>", new Symbol.Array("<Global Declaration>", "<S 1>")));
        grammar.addRule(new Rule("<S 1>", new Symbol.Array("<Global Declaration>", "<S 1>")));
        grammar.addRule(new Rule("<S 1>", new Symbol.Array("")));
        grammar.addRule(new Rule("<Global Declaration>", new Symbol.Array("<Start Def>")));
        grammar.addRule(new Rule("<Global Declaration>", new Symbol.Array("<Var Def>")));
        grammar.addRule(new Rule("<Global Declaration>", new Symbol.Array("<Const Def>")));
        grammar.addRule(new Rule("<Global Declaration>", new Symbol.Array("<Struct Def>")));
        grammar.addRule(new Rule("<Global Declaration>", new Symbol.Array("<Function Def>")));
        grammar.addRule(new Rule("<Global Declaration>", new Symbol.Array("<Procedure Def>")));
        grammar.addRule(new Rule("<Global Declaration>", new Symbol.Array("<Typedef Def>")));
        grammar.addRule(new Rule("<Function Def>", new Symbol.Array("'function'", "<Type>", "<Declarator>", "'('", "<Parameter List>", "')'", "'{'", "<Stmt Or Declaration List>", "'}'")));
        grammar.addRule(new Rule("<Procedure Def>", new Symbol.Array("'procedure'", "IDENTIFICADOR", "'('", "<Parameter List>", "')'", "'{'", "<Stmt Or Declaration List>", "'}'")));
        grammar.addRule(new Rule("<Typedef Def>", new Symbol.Array("'typedef'", "<Typedef Def lf>")));
        grammar.addRule(new Rule("<Typedef Def lf>", new Symbol.Array("<Type>", "IDENTIFICADOR", "';'")));
        grammar.addRule(new Rule("<Typedef Def lf>", new Symbol.Array("<Struct Def>", "IDENTIFICADOR", "';'")));
        grammar.addRule(new Rule("<Var Def>", new Symbol.Array("'var'", "'{'", "<Declaration List>", "'}'")));
        grammar.addRule(new Rule("<Const Def>", new Symbol.Array("'const'", "'{'", "<Declaration List>", "'}'")));
        grammar.addRule(new Rule("<Struct Def>", new Symbol.Array("'struct'", "IDENTIFICADOR", "<Struct Def lf>")));
        grammar.addRule(new Rule("<Struct Def lf>", new Symbol.Array("'{'", "<Declaration List>", "'}'")));
        grammar.addRule(new Rule("<Struct Def lf>", new Symbol.Array("'extends'", "IDENTIFICADOR", "'{'", "<Declaration List>", "'}'")));
        grammar.addRule(new Rule("<Parameter List>", new Symbol.Array("<Parameter Declaration>", "<Parameter List 1>")));
        grammar.addRule(new Rule("<Parameter List 1>", new Symbol.Array("','", "<Parameter Declaration>", "<Parameter List 1>")));
        grammar.addRule(new Rule("<Parameter List 1>", new Symbol.Array("")));
        grammar.addRule(new Rule("<Parameter Declaration>", new Symbol.Array("<Type>", "<Declarator>")));
        grammar.addRule(new Rule("<Declaration List>", new Symbol.Array("<Declaration>", "<Declaration List 1>")));
        grammar.addRule(new Rule("<Declaration List 1>", new Symbol.Array("<Declaration>", "<Declaration List 1>")));
        grammar.addRule(new Rule("<Declaration List 1>", new Symbol.Array("")));
        grammar.addRule(new Rule("<Declaration>", new Symbol.Array("<Type>", "<Init Declarator List>", "';'")));
        grammar.addRule(new Rule("<Init Declarator List>", new Symbol.Array("<Init Declarator>", "<Init Declarator List 1>")));
        grammar.addRule(new Rule("<Init Declarator List 1>", new Symbol.Array("','", "<Init Declarator>", "<Init Declarator List 1>")));
        grammar.addRule(new Rule("<Init Declarator List 1>", new Symbol.Array("")));
        grammar.addRule(new Rule("<Init Declarator>", new Symbol.Array("<Declarator>", "<Init Declarator lf>")));
        grammar.addRule(new Rule("<Init Declarator lf>", new Symbol.Array("'='", "<Initializer>")));
        grammar.addRule(new Rule("<Init Declarator lf>", new Symbol.Array("")));
        grammar.addRule(new Rule("<Initializer>", new Symbol.Array("<Assign Expr>")));
        grammar.addRule(new Rule("<Initializer>", new Symbol.Array("'{'", "<Initializer List>", "<Initializer lf>")));
        grammar.addRule(new Rule("<Initializer lf>", new Symbol.Array("'}'")));
        grammar.addRule(new Rule("<Initializer lf>", new Symbol.Array("','", "'}'")));
        grammar.addRule(new Rule("<Initializer List>", new Symbol.Array("<Initializer>", "<Initializer List 1>")));
        grammar.addRule(new Rule("<Initializer List 1>", new Symbol.Array("','", "<Initializer>", "<Initializer List 1>")));
        grammar.addRule(new Rule("<Initializer List 1>", new Symbol.Array("")));
        grammar.addRule(new Rule("<Declarator>", new Symbol.Array("IDENTIFICADOR", "<Declarator 1>")));
        grammar.addRule(new Rule("<Declarator 1>", new Symbol.Array("'['", "<Declarator 1 lf>")));
        grammar.addRule(new Rule("<Declarator 1>", new Symbol.Array("")));
        grammar.addRule(new Rule("<Declarator 1 lf>", new Symbol.Array("<Cond Expr>", "']'", "<Declarator 1>")));
        grammar.addRule(new Rule("<Declarator 1 lf>", new Symbol.Array("']'", "<Declarator 1>")));
        grammar.addRule(new Rule("<Stmt>", new Symbol.Array("<Iteration Stmt>")));
        grammar.addRule(new Rule("<Stmt>", new Symbol.Array("<Expr Stmt>")));
        grammar.addRule(new Rule("<Stmt>", new Symbol.Array("<Compound Stmt>")));
        grammar.addRule(new Rule("<Stmt>", new Symbol.Array("<Print Stmt>")));
        grammar.addRule(new Rule("<Stmt>", new Symbol.Array("<Scan Stmt>")));
        grammar.addRule(new Rule("<Stmt>", new Symbol.Array("<If Stmt>")));
        grammar.addRule(new Rule("<Stmt>", new Symbol.Array("<Return Stmt>")));
        grammar.addRule(new Rule("<Stmt Or Declaration List>", new Symbol.Array("<Stmt>", "<Stmt Or Declaration List 1>")));
        grammar.addRule(new Rule("<Stmt Or Declaration List>", new Symbol.Array("<Var Def>", "<Stmt Or Declaration List 1>")));
        grammar.addRule(new Rule("<Stmt Or Declaration List 1>", new Symbol.Array("<Stmt>", "<Stmt Or Declaration List 1>")));
        grammar.addRule(new Rule("<Stmt Or Declaration List 1>", new Symbol.Array("<Var Def>", "<Stmt Or Declaration List 1>")));
        grammar.addRule(new Rule("<Stmt Or Declaration List 1>", new Symbol.Array("")));
        grammar.addRule(new Rule("<Start Def>", new Symbol.Array("'start'", "'('", "')'", "'{'", "<Stmt Or Declaration List>", "'}'")));
        grammar.addRule(new Rule("<Print Stmt>", new Symbol.Array("'print'", "'('", "<Argument List>", "')'", "';'")));
        grammar.addRule(new Rule("<Scan Stmt>", new Symbol.Array("'scan'", "'('", "<Argument List>", "')'", "';'")));
        grammar.addRule(new Rule("<Iteration Stmt>", new Symbol.Array("'while'", "'('", "<Expr>", "')'", "<Stmt>")));
        grammar.addRule(new Rule("<If Stmt>", new Symbol.Array("'if'", "<Expr>", "'then'", "<Stmt>", "<If Stmt lf>")));
        grammar.addRule(new Rule("<If Stmt lf>", new Symbol.Array("'else'", "<Stmt>")));
        grammar.addRule(new Rule("<If Stmt lf>", new Symbol.Array("")));
        grammar.addRule(new Rule("<Return Stmt>", new Symbol.Array("'return'", "<Expr>", "';'")));
        grammar.addRule(new Rule("<Compound Stmt>", new Symbol.Array("'{'", "<Compound Stmt lf>")));
        grammar.addRule(new Rule("<Compound Stmt lf>", new Symbol.Array("'}'")));
        grammar.addRule(new Rule("<Compound Stmt lf>", new Symbol.Array("<Stmt Or Declaration List>", "'}'")));
        grammar.addRule(new Rule("<Expr Stmt>", new Symbol.Array("<Expr>", "';'")));
        grammar.addRule(new Rule("<Expr Stmt>", new Symbol.Array("';'")));
        grammar.addRule(new Rule("<Expr>", new Symbol.Array("<Assign Expr>", "<Expr 1>")));
        grammar.addRule(new Rule("<Expr 1>", new Symbol.Array("','", "<Assign Expr>", "<Expr 1>")));
        grammar.addRule(new Rule("<Expr 1>", new Symbol.Array("")));
        grammar.addRule(new Rule("<Assign Expr>", new Symbol.Array("<Cond Expr>")));
        grammar.addRule(new Rule("<Assign Expr>", new Symbol.Array("<Postfix Expr>", "'='", "<Assign Expr>")));
        grammar.addRule(new Rule("<Cond Expr>", new Symbol.Array("<Logical Or Expr>")));
        grammar.addRule(new Rule("<Logical Or Expr>", new Symbol.Array("<Logical And Expr>", "<Logical Or Expr 1>")));
        grammar.addRule(new Rule("<Logical Or Expr 1>", new Symbol.Array("'||'", "<Logical And Expr>", "<Logical Or Expr 1>")));
        grammar.addRule(new Rule("<Logical Or Expr 1>", new Symbol.Array("")));
        grammar.addRule(new Rule("<Logical And Expr>", new Symbol.Array("<Equal Expr>", "<Logical And Expr 1>")));
        grammar.addRule(new Rule("<Logical And Expr 1>", new Symbol.Array("'&&'", "<Equal Expr>", "<Logical And Expr 1>")));
        grammar.addRule(new Rule("<Logical And Expr 1>", new Symbol.Array("")));
        grammar.addRule(new Rule("<Equal Expr>", new Symbol.Array("<Relational Expr>", "<Equal Expr 1>")));
        grammar.addRule(new Rule("<Equal Expr 1>", new Symbol.Array("<Equal Op>", "<Relational Expr>", "<Equal Expr 1>")));
        grammar.addRule(new Rule("<Equal Expr 1>", new Symbol.Array("")));
        grammar.addRule(new Rule("<Relational Expr>", new Symbol.Array("<Additive Expr>", "<Relational Expr 1>")));
        grammar.addRule(new Rule("<Relational Expr 1>", new Symbol.Array("<Relational Op>", "<Additive Expr>", "<Relational Expr 1>")));
        grammar.addRule(new Rule("<Relational Expr 1>", new Symbol.Array("")));
        grammar.addRule(new Rule("<Additive Expr>", new Symbol.Array("<Mult Expr>", "<Additive Expr 1>")));
        grammar.addRule(new Rule("<Additive Expr 1>", new Symbol.Array("<Additive Op>", "<Mult Expr>", "<Additive Expr 1>")));
        grammar.addRule(new Rule("<Additive Expr 1>", new Symbol.Array("")));
        grammar.addRule(new Rule("<Mult Expr>", new Symbol.Array("<Unary Expr>", "<Mult Expr 1>")));
        grammar.addRule(new Rule("<Mult Expr 1>", new Symbol.Array("<Mult Op>", "<Unary Expr>", "<Mult Expr 1>")));
        grammar.addRule(new Rule("<Mult Expr 1>", new Symbol.Array("")));
        grammar.addRule(new Rule("<Unary Expr>", new Symbol.Array("<Unary Op>", "<Unary Expr>")));
        grammar.addRule(new Rule("<Unary Expr>", new Symbol.Array("<Postfix Expr>")));
        grammar.addRule(new Rule("<Postfix Expr>", new Symbol.Array("<Primary Expr>", "<Postfix Expr 1>")));
        grammar.addRule(new Rule("<Postfix Expr 1>", new Symbol.Array("<Postfix Op>", "<Postfix Expr 1>")));
        grammar.addRule(new Rule("<Postfix Expr 1>", new Symbol.Array("")));
        grammar.addRule(new Rule("<Primary Expr>", new Symbol.Array("IDENTIFICADOR")));
        grammar.addRule(new Rule("<Primary Expr>", new Symbol.Array("NUMERO")));
        grammar.addRule(new Rule("<Primary Expr>", new Symbol.Array("CADEIACARECTERES")));
        grammar.addRule(new Rule("<Primary Expr>", new Symbol.Array("'true'")));
        grammar.addRule(new Rule("<Primary Expr>", new Symbol.Array("'false'")));
        grammar.addRule(new Rule("<Primary Expr>", new Symbol.Array("'('", "<Expr>", "')'")));
        grammar.addRule(new Rule("<Equal Op>", new Symbol.Array("'=='")));
        grammar.addRule(new Rule("<Equal Op>", new Symbol.Array("'!='")));
        grammar.addRule(new Rule("<Relational Op>", new Symbol.Array("'<'")));
        grammar.addRule(new Rule("<Relational Op>", new Symbol.Array("'>'")));
        grammar.addRule(new Rule("<Relational Op>", new Symbol.Array("'>='")));
        grammar.addRule(new Rule("<Relational Op>", new Symbol.Array("'<='")));
        grammar.addRule(new Rule("<Relational Op>", new Symbol.Array("'<='")));
        grammar.addRule(new Rule("<Additive Op>", new Symbol.Array("'+'")));
        grammar.addRule(new Rule("<Additive Op>", new Symbol.Array("'-'")));
        grammar.addRule(new Rule("<Mult Op>", new Symbol.Array("'*'")));
        grammar.addRule(new Rule("<Mult Op>", new Symbol.Array("'/'")));
        grammar.addRule(new Rule("<Unary Op>", new Symbol.Array("'++'")));
        grammar.addRule(new Rule("<Unary Op>", new Symbol.Array("'--'")));
        grammar.addRule(new Rule("<Unary Op>", new Symbol.Array("'!'")));
        grammar.addRule(new Rule("<Postfix Op>", new Symbol.Array("'++'")));
        grammar.addRule(new Rule("<Postfix Op>", new Symbol.Array("'--'")));
        grammar.addRule(new Rule("<Postfix Op>", new Symbol.Array("'['", "<Expr>", "']'")));
        grammar.addRule(new Rule("<Postfix Op>", new Symbol.Array("'('", "<Postfix Op lf>")));
        grammar.addRule(new Rule("<Postfix Op>", new Symbol.Array("'.'", "IDENTIFICADOR")));
        grammar.addRule(new Rule("<Postfix Op lf>", new Symbol.Array("')'")));
        grammar.addRule(new Rule("<Postfix Op lf>", new Symbol.Array("<Argument List>", "')'")));
        grammar.addRule(new Rule("<Argument List>", new Symbol.Array("<Assign Expr>", "<Argument List 1>")));
        grammar.addRule(new Rule("<Argument List 1>", new Symbol.Array("','", "<Assign Expr>", "<Argument List 1>")));
        grammar.addRule(new Rule("<Argument List 1>", new Symbol.Array("")));
        grammar.addRule(new Rule("<Type>", new Symbol.Array("'int'")));
        grammar.addRule(new Rule("<Type>", new Symbol.Array("'string'")));
        grammar.addRule(new Rule("<Type>", new Symbol.Array("'float'")));
        grammar.addRule(new Rule("<Type>", new Symbol.Array("'bool'")));
        grammar.addRule(new Rule("<Type>", new Symbol.Array("IDENTIFICADOR")));

        grammar.setStartSymbol(new Symbol("<S>"));
        return grammar;
    }
}
